# Generated by Django 3.1.5 on 2021-01-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodTest',
        ),
    ]
