# Generated by Django 3.1.5 on 2021-01-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_payment', '0004_auto_20210111_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='amount',
        ),
    ]
