# Generated by Django 3.1.5 on 2021-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_payment', '0005_auto_20210111_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bkash',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
