# Generated by Django 2.2.5 on 2021-01-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonateOrgan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donateorgan',
            old_name='address',
            new_name='address_house',
        ),
        migrations.RenameField(
            model_name='donateorgan',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='donateorgan',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='donateorgan',
            old_name='needblood',
            new_name='organ_name',
        ),
        migrations.RenameField(
            model_name='donateorgan',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
