# Generated by Django 3.1.5 on 2021-01-08 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order_blood_test', '0002_remove_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='display_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Your display name', max_length=32),
            preserve_default=False,
        ),
    ]
