# Generated by Django 3.1.5 on 2021-01-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_blood_test', '0003_employee_display_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
