# Generated by Django 3.1.5 on 2021-01-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_blood_test', '0005_bloodtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtest',
            name='email',
        ),
    ]
