# Generated by Django 3.1.5 on 2021-01-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_blood_test', '0006_remove_bloodtest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
