# Generated by Django 3.1.5 on 2021-01-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_blood_test', '0007_bloodtest_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtest',
            name='bkash',
        ),
        migrations.RemoveField(
            model_name='bloodtest',
            name='trxid',
        ),
    ]
