# Generated by Django 3.1.5 on 2021-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_blood_test', '0008_auto_20210111_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
