# Generated by Django 3.1.5 on 2021-01-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_blood_test', '0009_bloodtest_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodtest',
            name='nid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
