# Generated by Django 3.1.5 on 2021-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_blood_test', '0010_bloodtest_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='nid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
