# Generated by Django 3.1.5 on 2021-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_blood_test', '0011_auto_20210112_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='nid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
